# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f0b0fd1fc7011332b141e4c1e2109835a6d9eca871ed98156bd61f064286729b820f7be2529051bb8c01107d8698667b4531b4023b1eb069c8fb4f4f0ee867

test:
  secret_key_base: 557beb5f1045b945cc56ad01816540e75a4a2ee04c136668d9a467274ee18da5967d3a6aeaddd1a0c2018661c5afc9df2f7cc39619fa9b8fba88af15ec34a05e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
